feat: middleware datacite
ezpaarse-project/ezpaarse-middlewares pull request #35
Opened 2022-07-25 13:28 UTC by felixleo22

2022-09-02 12:27 UTC, nojhamster requested changes

2022-09-02 12:27 UTC, nojhamster commented on datacite/index.js
> +    }
An exception may be thrown if the response is not as expected.

```suggestion
    const titles = result && result.attributes && result.attributes.titles;
    if (!Array.isArray(titles)) { return; }
    const titleData = titles.find((item) => (item && item.title));

    if (titleData) {
      ec['publication_title'] = titleData.title;
    }
```

2022-09-02 12:27 UTC, nojhamster commented on datacite/manifest.json
> +    { "name": "datacite-api-key" }
```suggestion
    { "name": "datacite-buffer-size" }
```

2022-09-02 12:27 UTC, nojhamster commented on datacite/README.md
> +```
This Readme should be updated for Datacite instead of ezUnpaywall

2022-09-09 08:07 UTC, felixleo22 commented
It's done

2022-10-11 12:26 UTC, merged